# Generated by Django 4.1.5 on 2023-02-07 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(help_text='The course of the quiz.', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='registrar.course'),
        ),
        migrations.AddField(
            model_name='message',
            name='accommodation',
            field=models.ForeignKey(blank=True, help_text='The accommodation assigned as part of this message.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='messages', to='exams.accommodation'),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The message author.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='request',
            field=models.ForeignKey(help_text='The request this message is for.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='exams.accommodationrequest'),
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='accommodation',
            field=models.ForeignKey(blank=True, help_text='The assigned accommodation.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='accommodation_requests', to='exams.accommodation'),
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='quiz',
            field=models.ForeignKey(help_text='The quiz being requested for accommodation.', on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_requests', to='exams.quiz'),
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='read_by',
            field=models.ManyToManyField(blank=True, help_text='Who has read the latest messages in this request.', related_name='read_accommodation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accommodationrequest',
            name='student',
            field=models.ForeignKey(help_text='The student requesting the accommodation.', on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='quiz',
            field=models.ForeignKey(help_text='The quiz being accommodated.', on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='exams.quiz'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('course', 'identifier'), name='quiz-course-identifier-unique'),
        ),
        migrations.AddConstraint(
            model_name='accommodationrequest',
            constraint=models.UniqueConstraint(fields=('quiz', 'student'), name='accommodation_request-quiz-student-unique'),
        ),
    ]
