# Generated by Django 4.1.2 on 2023-01-31 05:23

from django.db import migrations, models
import exams.models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Any file attachments to the message.",
                null=True,
                upload_to=exams.models.message_attachment_path,
            ),
        ),
    ]
