# Generated by Django 4.1.5 on 2023-02-07 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registrar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The course name.', max_length=128)),
                ('access_code', models.CharField(default=registrar.models.access_code_default, help_text='The joining access code.', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='CourseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='The number.', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='The year of the term.')),
                ('season', models.CharField(choices=[('FA', 'Fall'), ('JA', 'Winter'), ('SP', 'Spring'), ('SU', 'Summer')], help_text='The season of the term.', max_length=2)),
            ],
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('year', 'season'), name='term-year-season-unique'),
        ),
        migrations.AddField(
            model_name='courselisting',
            name='course',
            field=models.ForeignKey(help_text='The course.', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='registrar.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(help_text='The term.', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='registrar.term'),
        ),
        migrations.AddConstraint(
            model_name='courselisting',
            constraint=models.UniqueConstraint(fields=('course', 'number'), name='listing-course-number-unique'),
        ),
    ]
